import { CalendarDays, FileBarChart, Printer } from 'lucide-react'
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { dailyInspections, qualityDistribution, scans, sizeDistribution } from '../data/mockData'
import { ChartCard, DemoBadge, ExportButtons, PageHeader, StatCard, downloadCsv } from '../components/Ui'

export default function ReportsPage() {
  const exportReport = () => downloadCsv([['Egg ID', 'Weight (g)', 'Size', 'Quality', 'Device'], ...scans.map((scan) => [scan[1], scan[2], scan[3], scan[4], scan[5]])], 'eggministrator-report-jul-25-2026.csv')
  return (
    <div>
      <PageHeader title="Reports" description="Generate and export egg inspection reports" actions={<DemoBadge />} />
      <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
        <div className="flex flex-wrap gap-2"><button className="rounded-full border border-slate-200 px-4 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-50">Daily</button><button className="rounded-full border border-slate-200 px-4 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-50">Weekly</button><button className="rounded-full border border-slate-200 px-4 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-50">Monthly</button><button className="rounded-full bg-forest-800 px-4 py-1.5 text-xs font-semibold text-white">Custom Range</button></div>
        <div className="mt-4 grid gap-3 lg:grid-cols-[180px_180px_1fr_150px_auto]"><label className="relative"><span className="sr-only">Start date</span><input type="date" defaultValue="2026-07-19" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-600" /></label><label><span className="sr-only">End date</span><input type="date" defaultValue="2026-07-25" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-600" /></label><select className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-600"><option>All Sizes</option><option>Large</option><option>Jumbo</option></select><select className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-600"><option>All Quality</option><option>Good</option><option>Spoiled</option></select><button className="inline-flex items-center justify-center gap-2 rounded-lg bg-forest-800 px-4 py-2 text-sm font-semibold text-white hover:bg-forest-900"><FileBarChart size={16} />Generate Report</button></div>
      </section>
      <div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold text-slate-900">Report Summary</h2><p className="text-sm text-slate-500">Jul 19, 2026 – Jul 25, 2026</p></div><ExportButtons onCsv={exportReport} onPdf={() => window.print()} /></div>
      <div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Total Eggs" value="8,742" detail="For selected period" icon={CalendarDays} tone="green" /><StatCard label="Good Eggs" value="7,612" detail="87.1% of total" icon={FileBarChart} tone="green" /><StatCard label="Spoiled Eggs" value="1,130" detail="12.9% of total" icon={Printer} tone="red" /><StatCard label="Average Weight" value="56.7g" detail="Across all grades" icon={CalendarDays} tone="yellow" /><StatCard label="Spoilage %" value="12.9%" detail="Of all inspected" icon={FileBarChart} tone="orange" /></div>
      <div className="mt-4 grid gap-4 xl:grid-cols-2"><ChartCard title="Size Distribution"><div className="flex flex-col items-center gap-3 sm:flex-row"><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={sizeDistribution} dataKey="value" nameKey="name" outerRadius={95} innerRadius={55}>{sizeDistribution.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="grid w-full grid-cols-2 gap-2 text-xs">{sizeDistribution.map((item) => <div key={item.name} className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: item.color }} />{item.name}<span className="ml-auto font-semibold">{item.value}</span></div>)}</div></div></ChartCard><ChartCard title="Daily Inspections"><ResponsiveContainer width="100%" height={260}><BarChart data={dailyInspections} margin={{ left: -20 }}><XAxis dataKey="day" tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey="count" fill="#227849" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard></div>
    </div>
  )
}
