import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Database, Download, FileBarChart, FileText, Printer, RotateCcw, Save } from 'lucide-react'
import { useMemo, useState } from 'react'
import { historyScans, reportingPeriod } from '../data/mockData'
import { PageHeader, downloadCsv } from '../components/Ui'

const sizes = ['All Sizes', 'Peewee', 'Small', 'Medium', 'Large', 'Extra Large', 'Jumbo']
const qualities = ['All Quality', 'Good', 'Spoiled']
const reportTypes = ['Inspection Summary', 'Detailed Records', 'Quality Report', 'Size Report']
const groupOptions = ['Day', 'Week', 'Month', 'Size', 'Quality']
const defaultBuilder = { reportType: 'Inspection Summary', startDate: reportingPeriod.start, endDate: reportingPeriod.end, size: 'All Sizes', quality: 'All Quality', groupBy: 'Day', includeCharts: false, includeDetails: false }

const formatDate = (isoDate) => new Intl.DateTimeFormat('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${isoDate}T00:00:00Z`))
const formatShortMonth = (month) => new Intl.DateTimeFormat('en-US', { month: 'short', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${month}-01T00:00:00Z`))
const weekStart = (isoDate) => { const date = new Date(`${isoDate}T00:00:00Z`); date.setUTCDate(date.getUTCDate() - ((date.getUTCDay() + 6) % 7)); return date.toISOString().slice(0, 10) }

const filterScans = (scans, filters) => scans.filter((scan) => scan.date >= filters.startDate && scan.date <= filters.endDate && (filters.size === 'All Sizes' || scan.size === filters.size) && (filters.quality === 'All Quality' || scan.quality === filters.quality))

const getGroupDetails = (scan, groupBy) => {
  if (groupBy === 'Week') { const key = weekStart(scan.date); return { key, label: `Week of ${formatDate(key)}`, sort: key } }
  if (groupBy === 'Month') { const key = scan.date.slice(0, 7); return { key, label: formatShortMonth(key), sort: key } }
  if (groupBy === 'Size') return { key: scan.size, label: scan.size, sort: sizes.indexOf(scan.size) }
  if (groupBy === 'Quality') return { key: scan.quality, label: scan.quality, sort: qualities.indexOf(scan.quality) }
  return { key: scan.date, label: scan.displayDate, sort: scan.date }
}

const buildGroups = (scans, groupBy) => {
  const groups = new Map()
  scans.forEach((scan) => {
    const group = getGroupDetails(scan, groupBy)
    const current = groups.get(group.key) || { ...group, inspections: 0, good: 0, spoiled: 0, totalWeight: 0 }
    current.inspections += 1
    current.good += scan.quality === 'Good' ? 1 : 0
    current.spoiled += scan.quality === 'Spoiled' ? 1 : 0
    current.totalWeight += scan.weight
    groups.set(group.key, current)
  })
  return [...groups.values()].sort((first, second) => String(first.sort).localeCompare(String(second.sort), undefined, { numeric: true })).map((group) => ({ ...group, averageWeight: Number((group.totalWeight / group.inspections).toFixed(1)), spoilageRate: Number(((group.spoiled / group.inspections) * 100).toFixed(1)) }))
}

export default function ReportsPage() {
  const [builder, setBuilder] = useState(defaultBuilder)
  const [report, setReport] = useState(null)
  const updateBuilder = (key, value) => setBuilder((current) => ({ ...current, [key]: value }))
  const generateReport = () => setReport({ ...builder, generatedAt: new Date() })
  const resetBuilder = () => { setBuilder(defaultBuilder); setReport(null) }
  const reportScans = useMemo(() => report ? filterScans(historyScans, report) : [], [report])
  const groups = useMemo(() => report ? buildGroups(reportScans, report.groupBy) : [], [report, reportScans])
  const summary = useMemo(() => {
    const total = reportScans.length
    const good = reportScans.filter((scan) => scan.quality === 'Good').length
    const spoiled = total - good
    const totalWeight = reportScans.reduce((sum, scan) => sum + scan.weight, 0)
    const mostCommonGroup = groups.reduce((largest, group) => group.inspections > largest.inspections ? group : largest, { label: 'No data', inspections: 0 })
    return { total, good, spoiled, averageWeight: total ? Number((totalWeight / total).toFixed(1)) : 0, spoilageRate: total ? Number(((spoiled / total) * 100).toFixed(1)) : 0, mostCommonGroup }
  }, [reportScans, groups])
  const findings = report ? [`${summary.total.toLocaleString()} inspections match the selected report criteria.`, `${summary.mostCommonGroup.label} has the highest volume with ${summary.mostCommonGroup.inspections.toLocaleString()} inspections.`, `Spoilage rate for this report is ${summary.spoilageRate}%.`] : []
  const exportCsv = () => downloadCsv([['Date', 'Time', 'Egg ID', 'Weight (g)', 'Size', 'Quality', 'Device'], ...reportScans.map((scan) => [scan.displayDate, scan.time, scan.eggId, scan.weight, scan.size, scan.quality, scan.device])], 'eggministrator-report.csv')

  return (
    <div className="reports-page">
      <div className="reports-builder"><PageHeader title="Reports" description="Build a formal inspection report from selected records." /></div>
      <section className="reports-builder rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6">
        <div className="mb-5 flex items-center gap-2"><FileText size={19} className="text-forest-800" /><h2 className="font-bold text-slate-900">Report Builder</h2></div>
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label><span className="mb-1.5 block text-xs font-semibold text-slate-600">Report Type</span><select value={builder.reportType} onChange={(event) => updateBuilder('reportType', event.target.value)} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm">{reportTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-semibold text-slate-600">Start Date</span><input type="date" value={builder.startDate} onChange={(event) => updateBuilder('startDate', event.target.value)} className="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" /></label><label><span className="mb-1.5 block text-xs font-semibold text-slate-600">End Date</span><input type="date" value={builder.endDate} onChange={(event) => updateBuilder('endDate', event.target.value)} className="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" /></label><label><span className="mb-1.5 block text-xs font-semibold text-slate-600">Group By</span><select value={builder.groupBy} onChange={(event) => updateBuilder('groupBy', event.target.value)} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm">{groupOptions.map((option) => <option key={option}>{option}</option>)}</select></label></div>
        <div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><label><span className="mb-1.5 block text-xs font-semibold text-slate-600">Egg Size</span><select value={builder.size} onChange={(event) => updateBuilder('size', event.target.value)} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm">{sizes.map((size) => <option key={size}>{size}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-semibold text-slate-600">Quality</span><select value={builder.quality} onChange={(event) => updateBuilder('quality', event.target.value)} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm">{qualities.map((quality) => <option key={quality}>{quality}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-semibold text-slate-600">Device</span><select disabled className="w-full cursor-not-allowed rounded-lg border border-slate-200 bg-slate-100 px-3 py-2.5 text-sm text-slate-400"><option>Not Configured</option></select></label></div>
        <div className="mt-5 flex flex-col gap-4 border-t border-slate-100 pt-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-5"><label className="inline-flex items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={builder.includeCharts} onChange={(event) => updateBuilder('includeCharts', event.target.checked)} className="h-4 w-4 rounded border-slate-300 text-forest-800" />Include charts</label><label className="inline-flex items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" checked={builder.includeDetails} onChange={(event) => updateBuilder('includeDetails', event.target.checked)} className="h-4 w-4 rounded border-slate-300 text-forest-800" />Include detailed records</label></div><div className="flex gap-2"><button onClick={resetBuilder} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50"><RotateCcw size={16} />Reset</button><button onClick={generateReport} className="inline-flex items-center gap-2 rounded-lg bg-forest-800 px-4 py-2.5 text-sm font-semibold text-white hover:bg-forest-900"><FileBarChart size={16} />Generate Report</button></div></div>
      </section>
      {!report && <section className="mt-5 rounded-xl border border-dashed border-slate-300 bg-white/60 p-10 text-center"><FileText className="mx-auto text-slate-400" size={30} /><h2 className="mt-3 font-bold text-slate-700">Your report preview will appear here</h2><p className="mt-1 text-sm text-slate-500">Choose report settings above, then select Generate Report.</p></section>}
      {report && <section className="report-preview mt-5 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8"><div className="report-actions mb-6 flex flex-col gap-3 border-b border-slate-100 pb-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-slate-500">Report preview is ready for printing or export.</p><div className="flex flex-wrap gap-2"><button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-lg border border-green-700 bg-white px-3 py-2 text-sm font-semibold text-green-800"><Download size={16} />Export CSV</button><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm font-semibold text-red-700"><FileText size={16} />Export PDF</button><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700"><Printer size={16} />Print</button><button disabled title="Report saving will be added with the database integration." className="inline-flex cursor-not-allowed items-center gap-2 rounded-lg bg-slate-100 px-3 py-2 text-sm font-semibold text-slate-400"><Save size={16} />Save Report</button></div></div>
        <header className="border-b-2 border-forest-800 pb-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-forest-800">Eggministrator</p><h1 className="mt-1 text-2xl font-bold text-slate-900">{report.reportType}</h1><p className="mt-1 text-sm text-slate-500">Egg inspection monitoring and quality report</p></div><div className="rounded-lg bg-green-50 px-4 py-3 text-sm"><p className="font-semibold text-forest-900">Sample Data</p><p className="mt-1 text-slate-600">Prepared by: Admin User</p></div></div></header>
        <dl className="my-6 grid gap-4 border-b border-slate-100 pb-6 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-slate-500">Date Covered</dt><dd className="mt-1 font-semibold text-slate-900">{formatDate(report.startDate)} – {formatDate(report.endDate)}</dd></div><div><dt className="text-slate-500">Generated</dt><dd className="mt-1 font-semibold text-slate-900">{report.generatedAt.toLocaleString('en-PH', { timeZone: 'Asia/Manila' })}</dd></div><div><dt className="text-slate-500">Group By</dt><dd className="mt-1 font-semibold text-slate-900">{report.groupBy}</dd></div><div><dt className="text-slate-500">Data Source</dt><dd className="mt-1 inline-flex items-center gap-1 font-semibold text-slate-900"><Database size={14} />Sample Data</dd></div></dl>
        <section><h2 className="mb-3 text-base font-bold text-slate-900">Executive Summary</h2><div className="overflow-x-auto"><table className="w-full min-w-[580px] border-collapse text-sm"><tbody><tr className="border-y border-slate-200"><th className="bg-slate-50 px-3 py-2 text-left font-semibold">Total Inspections</th><td className="px-3 py-2">{summary.total.toLocaleString()}</td><th className="bg-slate-50 px-3 py-2 text-left font-semibold">Good Eggs</th><td className="px-3 py-2">{summary.good.toLocaleString()}</td><th className="bg-slate-50 px-3 py-2 text-left font-semibold">Spoiled Eggs</th><td className="px-3 py-2">{summary.spoiled.toLocaleString()}</td></tr><tr className="border-b border-slate-200"><th className="bg-slate-50 px-3 py-2 text-left font-semibold">Average Weight</th><td className="px-3 py-2">{summary.averageWeight}g</td><th className="bg-slate-50 px-3 py-2 text-left font-semibold">Spoilage Rate</th><td className="px-3 py-2">{summary.spoilageRate}%</td><th className="bg-slate-50 px-3 py-2 text-left font-semibold">Largest Group</th><td className="px-3 py-2">{summary.mostCommonGroup.label}</td></tr></tbody></table></div></section>
        <section className="mt-7"><h2 className="mb-3 text-base font-bold text-slate-900">Grouped Report</h2><div className="overflow-x-auto"><table className="w-full min-w-[700px] border-collapse text-sm"><thead className="border-y border-slate-200 bg-slate-50 text-left text-xs text-slate-600"><tr><th className="px-3 py-2.5">{report.groupBy}</th><th className="px-3 py-2.5 text-right">Inspections</th><th className="px-3 py-2.5 text-right">Good</th><th className="px-3 py-2.5 text-right">Spoiled</th><th className="px-3 py-2.5 text-right">Avg. Weight</th><th className="px-3 py-2.5 text-right">Spoilage Rate</th></tr></thead><tbody>{groups.map((group) => <tr key={group.key} className="border-b border-slate-100"><td className="px-3 py-2.5 font-medium text-slate-800">{group.label}</td><td className="px-3 py-2.5 text-right">{group.inspections}</td><td className="px-3 py-2.5 text-right text-green-700">{group.good}</td><td className="px-3 py-2.5 text-right text-red-600">{group.spoiled}</td><td className="px-3 py-2.5 text-right">{group.averageWeight}g</td><td className="px-3 py-2.5 text-right">{group.spoilageRate}%</td></tr>)}{groups.length === 0 && <tr><td colSpan="6" className="px-3 py-8 text-center text-slate-500">No records match the selected criteria.</td></tr>}</tbody></table></div></section>
        {report.includeCharts && <section className="mt-7"><h2 className="mb-3 text-base font-bold text-slate-900">Charts</h2><div className="rounded-lg border border-slate-200 p-4"><ResponsiveContainer width="100%" height={260}><BarChart data={groups} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" /><XAxis dataKey="label" tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey="inspections" fill="#227849" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></section>}
        {report.includeDetails && <section className="mt-7"><h2 className="mb-3 text-base font-bold text-slate-900">Detailed Records</h2><div className="overflow-x-auto"><table className="w-full min-w-[800px] border-collapse text-sm"><thead className="border-y border-slate-200 bg-slate-50 text-left text-xs text-slate-600"><tr><th className="px-3 py-2.5">Date</th><th className="px-3 py-2.5">Time</th><th className="px-3 py-2.5">Egg ID</th><th className="px-3 py-2.5 text-right">Weight</th><th className="px-3 py-2.5">Size</th><th className="px-3 py-2.5">Quality</th><th className="px-3 py-2.5">Device</th></tr></thead><tbody>{reportScans.map((scan) => <tr key={scan.eggId} className="border-b border-slate-100"><td className="px-3 py-2">{scan.displayDate}</td><td className="px-3 py-2">{scan.time}</td><td className="px-3 py-2 font-medium">{scan.eggId}</td><td className="px-3 py-2 text-right">{scan.weight}g</td><td className="px-3 py-2">{scan.size}</td><td className={`px-3 py-2 font-medium ${scan.quality === 'Good' ? 'text-green-700' : 'text-red-600'}`}>{scan.quality}</td><td className="px-3 py-2">{scan.device}</td></tr>)}</tbody></table></div></section>}
        <section className="mt-7 border-t border-slate-100 pt-6"><h2 className="mb-3 text-base font-bold text-slate-900">Key Findings</h2><ul className="space-y-2 text-sm text-slate-700">{findings.map((finding) => <li key={finding} className="flex gap-2"><span className="text-forest-800">•</span>{finding}</li>)}</ul></section>
      </section>}
    </div>
  )
}
